EUR = 'EUR'
USD = 'USD'
GBP = 'GBP'
SEPAEUR = 'SEPAEUR'

BTC = 'BTC'
XRP = 'XRP'
ETH = 'ETH'
USDT = 'USDT'

METHOD_MASTERCARD = 'mastercard'
METHOD_SEPA = 'sepa'
CRYPTO = (BTC, XRP, ETH)
FIAT = (EUR, USD, GBP)

FIAT_PREFIX = 'CARD'

SELL_CURRENCIES = (EUR,)
SELL_SEPA = {METHOD_SEPA: SELL_CURRENCIES}

OPERATION_BUY = 'buy'
OPERATION_SELL = 'sell'

PAIRS_BUY = {
    EUR: {
        METHOD_MASTERCARD: CRYPTO,
        METHOD_SEPA: CRYPTO,
    },
    USD: {
        METHOD_MASTERCARD: CRYPTO,
    },
    GBP: {
        METHOD_MASTERCARD: CRYPTO,
    }
}

PAIRS_SELL = {
    BTC: SELL_SEPA,
    XRP: SELL_SEPA,
    ETH: SELL_SEPA,
}
